CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path
from WEB import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.registrar_empleado, name='registrar_empleado'),
    path('listar/', views.listar_empleado, name='listar_empleado'),
    path('actualizar/<int:id>/', views.actualizar_empleado, name='actualizar_empleado'),
    path('eliminar/<int:id>/', views.eliminar_empleado, name='eliminar_empleado'),
    path('registrar_departamento/', views.registrar_departamento, name='registrar_departamento'),  # Nueva ruta
    path('listar_departamento/', views.listar_departamento, name='listar_departamento'),  # Nueva ruta
]

CRUD/WEB/models.py
from django.db import models

# Create your models here.
#Crearemos una nueva tabla para aplicar FK
class Departamento(models.Model):
    nombre_departamento = models.CharField(max_length=200)
    ubicacion= models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre_departamento
        #retorna el nombre del departamento




GENERO_OPCIONES = (
    ('masculino', 'Masculino'),
    ('femenino', 'Femenino'),
    ('otro', 'Otro')
)
    #Primer campo es el valor que se guarda en la base de datos
    #El segundo campo es el valor que se muestra al usuario

class Empleado(models.Model):
        nombre_empleado = models.CharField(max_length=200)
        #Nombre de empleado, tipo char, longitud máxima 200
        apellido_empleado = models.CharField(max_length=100)
        email_empleado = models.EmailField(max_length=50, unique=True)
        #Email de empleado, tipo email, longitud máxima 50
        edad_empleado = models.IntegerField()
        #Edad de empleado, tipo entero
        genero_empleado = models.CharField(max_length=80, choices=GENERO_OPCIONES)
        #Genero de empleado, tipo char, longitud máxima 80, opciones de genero
        salario_empleado = models.IntegerField(null=False, blank=False)
        #Salario de empleado, tipo entero, no nulo, no vacío
        fecha_registro = models.DateTimeField(auto_now_add=True, null=True, blank=True)
        #Fecha de registro, se establece automaticamente en fecha y hora actual al crear un registro
        ultima_modificacion = models.DateTimeField(auto_now=True)
        #Ultima modificación, se establece automaticamente en fecha y hora actual al modificar un registro
        
        #para vincular la tabla Departamento con la tabla Empleado
        departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
        #django identifica que la tabla Departamento es la tabla padre y la tabla Empleado es la tabla hija
        #on_delete=models.CASCADE, si se elimina un registro de la tabla padre, se eliminan todos los registros de la tabla hija
        #django por si solo identifica cual es la primary key de la tabla padre y la vincula con la tabla hija

CRUD/WEB/forms.py
from django import forms
from .models import Empleado, Departamento

class EmpleadoForm(forms.ModelForm):
    departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), empty_label="Seleccione un departamento")
    #forms.ModelChoiceField(queryset=Departamento.objects.all()) 
    #crea un campo de formulario que permite seleccionar un objeto de un queryset, en este caso Departamento.objects.all()
    class Meta:
        model = Empleado
        fields = ['nombre_empleado', 'apellido_empleado', 'email_empleado', 'edad_empleado', 'genero_empleado', 'salario_empleado','departamento']
        
class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = ['nombre_departamento', 'ubicacion']

CRUD/WEB/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Empleado, Departamento  # Importa el modelo Departamento
from .forms import EmpleadoForm, DepartamentoForm  # Importa el formulario DepartamentoForm

def registrar_departamento(request):  # Nueva vista para registrar departamentos
    if request.method == "POST":
        form = DepartamentoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_departamento')  # Redirige a la nueva vista listar_departamento
    else:
        form = DepartamentoForm()
    return render(request, 'registrar_departamento.html', {'form': form})

def listar_departamento(request):  # Nueva vista para listar departamentos
    departamentos = Departamento.objects.all()
    return render(request, 'listar_departamento.html', {'departamentos': departamentos})

def registrar_empleado(request): 
    if request.method == "POST":
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_empleado')
    else:
        form = EmpleadoForm()
    return render(request, 'registrar_empleado.html', {'form': form})

def listar_empleado(request):
    empleados = Empleado.objects.all()
    return render(request, 'listar_empleado.html', {'empleados': empleados})

def actualizar_empleado(request, id):
    empleado = get_object_or_404(Empleado, id=id)
    if request.method == "POST":
        form = EmpleadoForm(request.POST, instance=empleado)
        if form.is_valid():
            form.save()
            return redirect('listar_empleado')
    else:
        form = EmpleadoForm(instance=empleado)
    return render(request, 'actualizar_empleado.html', {'form': form})

def eliminar_empleado(request, id):
    empleado = Empleado.objects.get(id=id)
    empleado.delete()
    return redirect('listar_empleado')

CRUD/WEB/templates/actualizar_empleado.html
<!DOCTYPE html>
<html>
<head>
    <title>Actualizar Empleado</title>
</head>
<body>
    <h1>Actualizar Empleado</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar</button>
    </form>
</body>
</html>

CRUD/WEB/templates/listar_departamento.html
<div>
    <a href="/">Registrar Empleado</a> |
    <a href="/listar/">Listar Empleados</a> |
    <a href="/registrar_departamento/">Registrar Departamento</a> |
    <a href="/listar_departamento/">Listar Departamentos</a>
</div>
  
  <h2>Lista de Departamentos</h2>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre del Departamento</th>
        <th>Ubicación</th>
      </tr>
    </thead>
    <tbody>
      {% for departamento in departamentos %}
        <tr>
           <td>{{ departamento.id }}</td>
          <td>{{ departamento.nombre_departamento }}</td>
          <td>{{ departamento.ubicacion }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="2">No hay departamentos registrados.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

CRUD/WEB/templates/listar_empleado.html
<!DOCTYPE html>
<html>
<head>
    <title>Listar Empleados</title>
</head>
<body>
    <div>
        <a href="/">Registrar Empleado</a> |
        <a href="/listar/">Listar Empleados</a> |
        <a href="/registrar_departamento/">Registrar Departamento</a> |
        <a href="/listar_departamento/">Listar Departamentos</a>
    </div>
    <h1>Listar Empleados</h1>
    <table>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Edad</th>
            <th>Género</th>
            <th>Salario</th>
            <th>Fecha de Registro</th>
            <th>Última Modificación</th>
            <th>Departamento</th>
            <th>Acciones</th>
        </tr>
        {% for empleado in empleados %}
        <tr>
            <td>{{ empleado.nombre_empleado }}</td>
            <td>{{ empleado.apellido_empleado }}</td>
            <td>{{ empleado.email_empleado }}</td>
            <td>{{ empleado.edad_empleado }}</td>
            <td>{{ empleado.get_genero_empleado_display }}</td>
            <td>{{ empleado.salario_empleado }}</td>
            <td>{{ empleado.fecha_registro }}</td>
            <td>{{ empleado.ultima_modificacion }}</td>
            <td>{{ empleado.departamento.id }}</td>
            <td>
                <a href="{% url 'actualizar_empleado' id=empleado.id %}">
                    <button>Actualizar</button>
                </a>
                <a href="{% url 'eliminar_empleado' id=empleado.id %}">
                    <button>Eliminar</button>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

CRUD/WEB/templates/registrar_departamento.html
<div>
    <a href="/">Registrar Empleado</a> |
    <a href="/listar/">Listar Empleados</a> |
    <a href="/registrar_departamento/">Registrar Departamento</a> |
    <a href="/listar_departamento/">Listar Departamentos</a>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrar</button>
</form>

CRUD/WEB/templates/registrar_empleado.html
<!DOCTYPE html>
<html>
<head>
    <title>Registrar Empleado</title>
</head>
<body>
    <div>
        <a href="/">Registrar Empleado</a> |
        <a href="/listar/">Listar Empleados</a> |
        <a href="/registrar_departamento/">Registrar Departamento</a> |
        <a href="/listar_departamento/">Listar Departamentos</a>
    </div>
    <h1>Registrar Empleado</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
</body>
</html>